packages:
  - "packages/*"
  - "deployers/*"
  - "stores/*"
  - "speech/*"
  - "voice/*"
  - "client-sdks/*"
  - "!packages/cli/admin"
  - "integrations/*"
  - "examples/*"
  - "examples/voice/*"
  - "examples/basics/**/*"
  - "examples/basics/llms/*"
  - "examples/voice/*"
  - "packages/cli/src/playground"
  - "packages/*/integration-tests"
  - "!examples/crypto-chatbot"
  - "!examples/travel-app"
  - "pj-management"